### ISSUE TITLE
Compile error, loclog is missing

### ISSUE THREAD

**Issue by mikkelrobin** [onlinecity/cpp-smpp#2]
Hi.

When running make, ill get the following error:

root@cpp-smpp:~/cpp-smpp# make
Linking CXX shared library libsmpp.so
/usr/bin/ld: cannot find -loclog
collect2: ld returned 1 exit status
make[2]: **\* [src/libsmpp.so.1.0.0] Error 1
make[1]: **\* [src/CMakeFiles/smpp.dir/all] Error 2
make: **\* [all] Error 2

**Comment by duerlund** [comment]
Hello,

We forgot to list our logging system OcLog as a dependency. Grab it here https://github.com/onlinecity/oclog
