### ISSUE TITLE
Problem running tests

### ISSUE THREAD

**Issue by mikkelrobin** [onlinecity/cpp-smpp#3]
Hi.

I got the cpp-smpp complied with no errors - but when running, make test, i got the following errors in Testing/Temporary/LastTest.log 
## Test time =   0.01 sec

Test Passed.
"cpp-unit-test" end time: Aug 21 11:03 CEST
## "cpp-unit-test" time elapsed: 00:00:00

2/2 Testing: live-test
2/2 Test: live-test
Command: "/root/cpp-smpp/test/livetest"
Directory: /root/cpp-smpp/test
"live-test" start time: Aug 21 11:03 CEST
## Output:

terminate called after throwing an instance of 'boost::exception_detail::clone_implboost::exception_detail::error_info_injector<boost::system::system_error >'
  what():  Invalid argument
<end of output>
## Test time =   0.09 sec

Test Failed.
"live-test" end time: Aug 21 11:03 CEST
## "live-test" time elapsed: 00:00:00

End testing: Aug 21 11:03 CEST

I also tried to compile the transmit.cpp script, but this fails because of a missing GsmEncoder class, witch, as i see it, is present.

root@cpp-smpp:~/smpp-clients# g++ transmit.cpp -I/usr/local/include -lsmpp -lboost_system -lboost_regex -lboost_date_time
transmit.cpp: In function ‘int main(int, char**)’:
transmit.cpp:33:46: error: ‘GsmEncoder’ has not been declared

**Comment by duerlund** [comment]
We changed the namespace of the GsmEncoder class a while ago, but we forgot to update our examples. I just updated our examples to reflect this.

**Comment by mikkelrobin** [comment]
Thanks.

But im still returning to the same issues, as when im running "make test"

terminate called after throwing an instance of 'boost::exception_detail::clone_implboost::exception_detail::error_info_injector<boost::system::system_error >'
  what():  Invalid argument
Aborted (core dumped)

**Comment by duerlund** [comment]
Removed all boost and switched the test system.

**Comment by ghost** [comment]
Hi,

How do i execute the 'make' when there is no configure file?
I get error in executing make than i can not continue?
