### ISSUE TITLE
CSMS_16BIT_TAGS unsupported?

### ISSUE THREAD

**Issue by cypres** [onlinecity/cpp-smpp#7]
``` c++
if (csms_method_ == CSMS_8BIT_UDH) {
    pdu << (params.esm_class | ESM_UHDI);  // Set UHDI bit
  } else {
    pdu << params.esm_class;
  }
```

At first glance it would seem CSMS_16BIT_TAGS are unsupported, but these are actually put in the TLV fields.

Test that each CSMS method works.

**Comment by duerlund** [comment]
Fixed in https://github.com/onlinecity/cpp-smpp/commit/03507442b3f166357c2e80c807abe79967964cd5
